on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    strategy:
      matrix:
        toolchain: [stable, nightly, 1.86.0]
        os: [ubuntu-24.04, windows-2022]
    
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
    - name: Check
      run: cargo xtask ci
    - name: Run tests
      run: cargo test
